modLoader = "javafml"
loaderVersion = "[42,)"

license = "All rights reserved"

[[mods]]
modId = "robotics"
version = "${file.jarVersion}"

displayName = "Create Robotics"
logoFile = "icon.png"

authors = "Workert, OutCraft, RealDarkStudios"

credits = "Thanks to darkMode for the amazing Tin Block and Program item textures!"

description = '''
Create Robotics is a mod about Robots and Robotics Automation in Minecraft using the Create mod.
Robots have many uses, some help you at specific tasks, some automate your factory and some fight your enemies.
Create Robotics has also a system planned for you to build and code your own robots.
'''


[[dependencies.robotics]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.1.39,4.0.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.robotics]]
modId = "create"
mandatory = true
versionRange = "[0.5.0.i,0.5.0.k)"
ordering = "NONE"
side = "BOTH"

[[dependencies.robotics]]
modId = "forge"
mandatory = true
versionRange = "[42,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.robotics]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
